name: cd

on:
  release:
    types: [published]

jobs:
  deploy:

    runs-on: ubuntu-latest

    env:
      CI: true
      VERSION_COMMIT: ${{ github.sha }}
      REGISTRY: ghcr.io

    steps:
      - name: Set VERSION env var
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - uses: actions/setup-node@v1
        with:
          node-version: 12.14

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        run: npm run docker:build

      - name: Push docker image
        run: npm run docker:push
