name: ci

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    env:
      CI: true

    steps:
      - name: Set additional environment variables
        run: |
          echo "NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV
          echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "VERSION_COMMIT=${GITHUB_SHA::8}" >> $GITHUB_ENV
          echo "VERSION_BUILD_DATE=$(date)" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.14

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install NPM dependencies
        run: npm ci

      - name: Build source code
        run: npm run build --if-present

      - name: Test source code
        run: npm test

      - name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          file: ./share/docker/Dockerfile
          context: .
          load: true
          platforms: linux/amd64
          tags: ${{ env.VERSION_COMMIT }}
          build-args: |
            NPM_TOKEN=${{ secrets.NPM_TOKEN }}
            NAME=${{ env.NAME }}
            VERSION=${{ env.VERSION }}
            VERSION_COMMIT=${{ env.VERSION_COMMIT }}
            VERSION_BUILD_DATE=${{ env.VERSION_BUILD_DATE }}

      - name: Test Docker image
        run: |
          docker run --rm --entrypoint "./test.sh" ${{ env.VERSION_COMMIT }}

      - name: Submit coveralls test coverage report
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if release should be created
        run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
